'use client';
import { useEffect, useMemo, useState } from 'react';
import { RotateCcw, Shield, Sparkles, Volume2, VolumeX, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
type Die={id:number;value:number;shield:boolean}; type Board=[Die[],Die[],Die[]]; type Player='me'|'cpu'; type Phase='place'|'shield'|'over';
const emptyBoard=():Board=>[[],[],[]]; const roll=()=>Math.floor(Math.random()*6)+1; const full=(b:Board)=>b.every(r=>r.length===3);
function rowScore(row:Die[]){const counts=row.reduce<Record<number,number>>((a,d)=>{a[d.value]=(a[d.value]||0)+1;return a},{});return row.reduce((s,d)=>s+d.value*(counts[d.value]||1),0)}
function comboMultiplier(row:Die[]){const counts=row.reduce<Record<number,number>>((a,d)=>{a[d.value]=(a[d.value]||0)+1;return a},{});return Math.max(1,...Object.values(counts))}
function DieFace({die,active=false}:{die:Die;active?:boolean}){return <div className={`die die-${die.value} ${die.shield?'shield-die':''} ${active?'active-die':''}`}>{die.shield&&<Shield className="shield-mark" aria-label="실드"/>}{Array.from({length:die.value}).map((_,i)=><span key={i} className="pip"/>)}</div>}
function MiniDie({value}:{value:number}){return <span className={`mini-die mini-${value}`}>{Array.from({length:value}).map((_,i)=><i key={i}/>)}</span>}
export default function Home(){
 const [boards,setBoards]=useState<{me:Board;cpu:Board}>({me:emptyBoard(),cpu:emptyBoard()}); const [turn,setTurn]=useState<Player>('me'); const [phase,setPhase]=useState<Phase>('place'); const [value,setValue]=useState(1); const [isShield,setIsShield]=useState(true); const [rerolls,setRerolls]=useState({me:true,cpu:true}); const [choice,setChoice]=useState<number[]|null>(null); const [message,setMessage]=useState('첫 주사위는 실드입니다. 내 보드에 놓아주세요.'); const [rulesOpen,setRulesOpen]=useState(false); const [sound,setSound]=useState(true); const [gameNo,setGameNo]=useState(1);
 useEffect(()=>{setValue(roll())},[]);
 const scores=useMemo(()=>({me:boards.me.map(rowScore),cpu:boards.cpu.map(rowScore)}),[boards]);
 const nextTurn=(nextBoards:{me:Board;cpu:Board},current:Player)=>{if(full(nextBoards.me)&&full(nextBoards.cpu)){setPhase('over');setMessage('게임 종료! 최종 결과를 확인하세요.');return}let next:Player=current==='me'?'cpu':'me';if(full(nextBoards[next]))next=current;setTurn(next);setPhase('place');setIsShield(false);setChoice(null);setValue(roll());setMessage(next==='me'?'내 차례입니다. 주사위를 놓을 줄을 선택하세요.':'상대가 수를 고민하고 있습니다…')};
 const place=(owner:Player,rowIndex:number)=>{if(phase==='over'||turn!=='me'||choice)return;const initial=boards.me.flat().length===0&&boards.cpu.flat().length===0;if((owner!=='me'&&!isShield)||(initial&&owner!=='me')||boards[owner][rowIndex].length>=3)return;const next={me:boards.me.map(r=>[...r]) as Board,cpu:boards.cpu.map(r=>[...r]) as Board};next[owner][rowIndex].push({id:Date.now()+Math.random(),value,shield:isShield});let knocked=0;if(!isShield&&owner==='me'){const before=next.cpu[rowIndex].length;next.cpu[rowIndex]=next.cpu[rowIndex].filter(d=>d.shield||d.value!==value);knocked=before-next.cpu[rowIndex].length}setBoards(next);if(knocked){setPhase('shield');setIsShield(true);setValue(roll());setMessage(`알까기 성공! ${knocked}개 제거 · 보너스 실드를 양쪽 보드 중 골라 놓으세요.`)}else nextTurn(next,'me')};
 useEffect(()=>{if(turn!=='cpu'||phase==='over')return;const timer=setTimeout(()=>{const next={me:boards.me.map(r=>[...r]) as Board,cpu:boards.cpu.map(r=>[...r]) as Board};const open=next.cpu.map((r,i)=>r.length<3?i:-1).filter(i=>i>=0);if(!open.length){nextTurn(next,'cpu');return}const row=open.sort((a,b)=>next.me[b].filter(d=>!d.shield&&d.value===value).length-next.me[a].filter(d=>!d.shield&&d.value===value).length||rowScore(next.cpu[b])-rowScore(next.cpu[a]))[0];next.cpu[row].push({id:Date.now(),value,shield:isShield});let knocked=0;if(!isShield){const before=next.me[row].length;next.me[row]=next.me[row].filter(d=>d.shield||d.value!==value);knocked=before-next.me[row].length}if(knocked){const sv=roll();const own=next.cpu.map((r,i)=>r.length<3?i:-1).filter(i=>i>=0);const yours=next.me.map((r,i)=>r.length<3?i:-1).filter(i=>i>=0);const target:Player=own.length?'cpu':'me';const rows=target==='cpu'?own:yours;if(rows.length)next[target][rows[0]].push({id:Date.now()+1,value:sv,shield:true});setMessage(`상대가 알까기로 ${knocked}개를 제거하고 실드를 배치했습니다.`)}setBoards({me:next.me.map(r=>[...r]) as Board,cpu:next.cpu.map(r=>[...r]) as Board});nextTurn(next,'cpu')},720);return()=>clearTimeout(timer)},[turn,phase,value,isShield,boards]);
 const useReroll=()=>{if(turn!=='me'||!rerolls.me||phase==='over')return;setRerolls(r=>({...r,me:false}));setChoice([value,roll()]);setMessage('기존 숫자와 새 숫자 중 하나를 선택하세요.')};
 const reset=()=>{setBoards({me:emptyBoard(),cpu:emptyBoard()});setTurn('me');setPhase('place');setValue(roll());setIsShield(true);setRerolls({me:true,cpu:true});setChoice(null);setMessage('첫 주사위는 실드입니다. 내 보드에 놓아주세요.');setGameNo(n=>n+1)};
 const wins=[0,1,2].reduce((a,i)=>{if(scores.me[i]>scores.cpu[i])a.me++;else if(scores.cpu[i]>scores.me[i])a.cpu++;return a},{me:0,cpu:0});const totals={me:scores.me.reduce((a,b)=>a+b,0),cpu:scores.cpu.reduce((a,b)=>a+b,0)};const finalWinner=wins.me>=2?'내 승리':wins.cpu>=2?'상대 승리':totals.me>totals.cpu?'내 승리':totals.cpu>totals.me?'상대 승리':'무승부';
 return <main className="game-shell"><header className="topbar"><div className="brand"><span className="brand-gem"><Sparkles/></span><div><h1>룬 다이스</h1><p>세 줄의 운명</p></div></div><div className="round-chip">ROUND <strong>{gameNo}</strong></div><nav><Button variant="ghost" size="sm" onClick={()=>setRulesOpen(true)}>게임 규칙</Button><Button variant="ghost" size="icon-sm" onClick={()=>setSound(!sound)} aria-label="소리 켜기/끄기">{sound?<Volume2/>:<VolumeX/>}</Button><Button variant="ghost" size="icon-sm" onClick={reset} aria-label="새 게임"><RotateCcw/></Button></nav></header>
 <section className="turn-stage"><span className={`turn-dot ${turn==='me'?'mine':''}`}/><div><p>{turn==='me'?'당신의 차례':'상대의 차례'}</p><strong>{message}</strong></div><span className={`type-badge ${isShield?'shield':''}`}>{isShield&&<Shield/>}{isShield?'실드 주사위':'일반 주사위'}</span></section>
 <section className="table-wrap"><PlayerBoard label="나" sub="항상 왼쪽" board={boards.me} scores={scores.me} accent="teal" active={turn==='me'} onRow={i=>place('me',i)} canPlace={i=>turn==='me'&&!choice&&boards.me[i].length<3} currentValue={value}/><div className="center-console"><span className="roll-label">이번 주사위</span><DieFace die={{id:0,value,shield:isShield}} active/>{choice?<div className="choice-box"><p>어떤 숫자를 둘까요?</p><div>{choice.map((n,i)=><button key={`${n}-${i}`} onClick={()=>{setValue(n);setChoice(null);setMessage('선택한 주사위를 놓아주세요.')}}><MiniDie value={n}/><b>{i?'새 숫자':'기존'}</b></button>)}</div></div>:<Button className="reroll-btn" variant="outline" onClick={useReroll} disabled={!rerolls.me||turn!=='me'}><RotateCcw/> 리롤 <small>{rerolls.me?'1회 남음':'사용 완료'}</small></Button>}<div className="versus">VS</div></div><PlayerBoard label="상대" sub="CPU" board={boards.cpu} scores={scores.cpu} accent="coral" active={turn==='cpu'} onRow={i=>place('cpu',i)} canPlace={i=>turn==='me'&&!choice&&isShield&&boards.cpu[i].length<3&&!(boards.me.flat().length===0&&boards.cpu.flat().length===0)} currentValue={value}/></section>
 <footer className="scorebar"><div><span>획득 라인</span><strong className="teal-text">{wins.me}</strong><i>:</i><strong className="coral-text">{wins.cpu}</strong></div><p>같은 숫자 더블 ×2 · 트리플 ×3</p><div><span>총점</span><strong>{totals.me}</strong><i>:</i><strong>{totals.cpu}</strong></div></footer>
 {phase==='over'&&<div className="modal-backdrop"><section className="result-card"><Sparkles/><p>게임 종료</p><h2>{finalWinner}</h2><div><span>획득 라인 {wins.me} : {wins.cpu}</span><span>총점 {totals.me} : {totals.cpu}</span></div><Button onClick={reset}>다시 대결하기</Button></section></div>}{rulesOpen&&<div className="modal-backdrop" onClick={()=>setRulesOpen(false)}><section className="rules-card" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setRulesOpen(false)} aria-label="닫기"><X/></button><p className="eyebrow">HOW TO PLAY</p><h2>게임 규칙</h2><ol><li><b>줄을 차지하세요</b><span>각 줄에 주사위를 3개까지 놓고, 3줄 중 2줄 이상 높은 점수를 만드세요.</span></li><li><b>더블 · 트리플 보너스</b><span>같은 줄에 같은 숫자 2개가 모이면 그 숫자 합계에 ×2, 3개면 ×3을 적용합니다. 예: 4+4는 16점, 4+4+4는 36점입니다.</span></li><li><b>알까기</b><span>일반 주사위를 내 줄에 놓으면 상대 같은 줄의 동일 숫자 일반 주사위를 모두 제거합니다.</span></li><li><b>실드 주사위</b><span>알까기에 제거되지 않으며, 보상 실드는 양쪽 보드 어디든 놓을 수 있습니다.</span></li><li><b>단 한 번의 리롤</b><span>게임당 한 번, 기존 숫자와 새 숫자 중 원하는 것을 선택할 수 있습니다.</span></li></ol></section></div>}</main>}
function PlayerBoard({label,sub,board,scores,accent,active,onRow,canPlace,currentValue}:{label:string;sub:string;board:Board;scores:number[];accent:string;active:boolean;onRow:(i:number)=>void;canPlace:(i:number)=>boolean;currentValue:number}){return <section className={`player-side ${accent} ${active?'turn-active':''}`}><header><div className="avatar">{label==='나'?'✦':'◆'}</div><div><h2>{label}</h2><p>{sub}</p></div><span>{active?'TURN':''}</span></header><div className="board">{board.map((row,i)=>{const combo=comboMultiplier(row);return <button key={i} className={`row ${canPlace(i)?'placeable':''} ${combo>1?'combo-row':''}`} onClick={()=>onRow(i)} disabled={!canPlace(i)} aria-label={`${i+1}번째 줄에 놓기`}><span className="row-num">0{i+1}</span><div className="slots">{[0,1,2].map(slot=>row[slot]?<DieFace key={row[slot].id} die={row[slot]}/>:<span key={slot} className="slot">{canPlace(i)&&slot===row.length?<span className="ghost-value">{currentValue}</span>:null}</span>)}</div><div className="row-score">{combo>1&&<em className={`combo-badge combo-${combo}`}>{combo===3?'TRIPLE':'DOUBLE'} ×{combo}</em>}<small>SCORE</small><strong>{scores[i]}</strong></div></button>})}</div></section>}
